baseURL: /
languageCode: en-us
theme: raditian-free-hugo-theme-data-science
params:
  footer:
    copyright: © DataIQ. All rights reserved.
    site_logo:
      _2x: img/general/logo-png.png
      alt: Design & Code -  DataIQ
      x: img/general/logo-png.png
  googleAnalyticsID: ''
  logo:
    text1: DataIQ - AI/ML  
    text2: --------
  plugins:
    css:
      - URL: css/main.css
      - URL: css/rad-icons.css
      - URL: css/custom.css
    js:
      - URL: js/rad-animations.js
      - URL: js/sticky-header.js
      - URL: js/library/fontfaceobserver.js
  sections:
    - showcase
    - about
    - client-and-work
    - experience
    - education
    - testimonial
    - contact
    - newsletter
menu:
  footer:
    - URL: '#about'
      name: About
      weight: 2
    - URL: '#portfolio'
      name: Portfolio
      weight: 3
    - URL: '#experience'
      name: Services
      weight: 4
    # - URL: '#testimonial'
    #   name: Testimonials
    #   weight: 5
    - URL: '#contact'
      name: Contact
      weight: 5
  header:
    - URL: '#about'
      name: About
      weight: 2
    - URL: '#portfolio'
      name: Portfolio
      weight: 3
    - URL: '#experience'
      name: Services
      weight: 4
    # - URL: '#testimonial'
    #   name: Testimonials
    #   weight: 5
    - URL: '#contact'
      name: Contact
      weight: 5
