baseURL = "/"
languageCode = "en-us"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3
  
  [[menu.header]]
  name = "Testimonials"
  URL = "#testimonial"
  weight = 4

  [[menu.header]]
  name = "Contact"
  URL = "#contact"
  weight = 5


  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3
  
  [[menu.footer]]
  name = "Testimonials"
  URL = "#testimonial"
  weight = 4

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 5


[params]

  sections = ["showcase", "about", "client-and-work", "experience", "education",  "testimonial", "contact", "newsletter"]

  googleAnalyticsID = "" 

  [params.logo]
    text1 = "Fatih"
    text2 = "Uenal"

  [params.footer]
      copyright = "© Fatih Uenal. All rights reserved."
      [params.footer.site_logo]
        x = "img/generallogo-transparent-png.png.png"
        _2x = "img/general/logo-transparent-png.png.png"
        alt = "Design & Code - The Dataist"
  
  